In [2]:
from pathlib import Path
import pandas as pd

raw_dir = Path("../data/raw")

files = [
    "disaster_declarations_summaries.csv",
    "public_assistance_funded_projects_details.csv",
    "fema_web_disaster_summaries.csv",
]

for file_name in files:
    file_path = raw_dir / file_name
    print(f"\nChecking {file_name}")
    print("Exists:", file_path.exists())

    if file_path.exists():
        df = pd.read_csv(file_path)
        print("Shape:", df.shape)
        print("Columns:", len(df.columns))
        display(df.head(2))

Checking disaster_declarations_summaries.csv
Exists: True
Shape: (69770, 28)
Columns: 28

,femaDeclarationString,disasterNumber,state,declarationType,declarationDate,fyDeclared,incidentType,declarationTitle,ihProgramDeclared,iaProgramDeclared,...,placeCode,designatedArea,declarationRequestNumber,lastIAFilingDate,incidentId,region,designatedIncidentTypes,lastRefresh,hash,id
0,FM-5529-OR,5529,OR,FM,2024-08-09T00:00:00.000Z,2024,Fire,LEE FALLS FIRE,False,False,...,99067,Washington (County),24122,NaN,2024081001,10,R,2024-08-27T18:22:14.800Z,ae87cf3c6ed795015b714af7166c7c295b2b67c7,09e3f81a-5e16-4b72-b317-1c64e0cfa59c
1,FM-5528-OR,5528,OR,FM,2024-08-06T00:00:00.000Z,2024,Fire,ELK LANE FIRE,False,False,...,99031,Jefferson (County),24116,NaN,2024080701,10,R,2024-08-27T18:22:14.800Z,432cf0995c47e3895cea696ede5621b810460501,59983f89-30bf-4888-b21b-62e8d57d9aac

Checking public_assistance_funded_projects_details.csv
Exists: True
Shape: (810787, 25)
Columns: 25

,disasterNumber,declarationDate,incidentType,pwNumber,applicationTitle,applicantId,damageCategoryCode,damageCategoryDescrip,projectStatus,projectProcessStep,...,projectAmount,federalShareObligated,totalObligated,lastObligationDate,firstObligationDate,mitigationAmount,gmProjectId,gmApplicantId,lastRefresh,hash
0,1239,1998-08-26T00:00:00.000Z,Severe Storm(s),1,(PW# 1) IMMEDIATE NEEDS FUNDING,465-19792-00,B,Emergency Protective Measures,Active,Project Closed Out,...,100000.0,75000.00,80340.0,1998-09-15T14:25:07.000Z,1998-09-15T14:25:07.000Z,0.0,1021769,268458,2025-11-27T15:05:59.253Z,addcfded82ae348f46ff034a4564f983a9dea897
1,1239,1998-08-26T00:00:00.000Z,Severe Storm(s),5,(PW# 5) Not Provided,465-19792-00,G,"Parks, Recreational Facilities, and Other Items",Active,Project Closed Out,...,19685.5,14764.13,15461.0,1998-09-23T08:58:52.000Z,1998-09-23T08:58:52.000Z,0.0,1062596,268458,2025-11-27T15:05:59.253Z,05c6c522b930a9c38b52a0c4b0de853e98b4cb75

Checking fema_web_disaster_summaries.csv
Exists: True
Shape: (3909, 14)
Columns: 14

,disasterNumber,totalNumberIaApproved,totalAmountIhpApproved,totalAmountHaApproved,totalAmountOnaApproved,totalObligatedAmountPa,totalObligatedAmountCatAb,totalObligatedAmountCatC2g,paLoadDate,iaLoadDate,totalObligatedAmountHmgp,hash,lastRefresh,id
0,3601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3de68baba960e69da445cf822d3dd859081fb34a,2023-10-09T23:02:26.341Z,faafecca-0f76-4fb8-8ffd-b6f46f3b712c
1,3602,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58566c446fce5cabbd0c3412a6bb3daa4ada1993,2023-10-09T23:02:26.341Z,b74f0dc2-fab5-42b9-acf7-c94df14d85ad

In [3]:
import pandas as pd

df_decl = pd.read_csv("../data/raw/disaster_declarations_summaries.csv")
df_pa = pd.read_csv("../data/raw/public_assistance_funded_projects_details.csv")
df_sum = pd.read_csv("../data/raw/fema_web_disaster_summaries.csv")

print("Declarations:", df_decl.shape)
print("Public Assistance:", df_pa.shape)
print("Summaries:", df_sum.shape)

print("\nKey column check:")
print("disasterNumber in declarations:", "disasterNumber" in df_decl.columns)
print("disasterNumber in PA:", "disasterNumber" in df_pa.columns)
print("disasterNumber in summaries:", "disasterNumber" in df_sum.columns)

Declarations: (69770, 28)
Public Assistance: (810787, 25)
Summaries: (3909, 14)

Key column check:
disasterNumber in declarations: True
disasterNumber in PA: True
disasterNumber in summaries: True